version: '3.7'

services:
  default: &default
    build: &build
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:80
    tty: true
    volumes:
      - ./src/begateway.php:/var/www/html/begateway.php
      - ./src/lang/russian/modules/payment/begateway.php:/var/www/html/lang/russian/modules/payment/begateway.php
      - ./src/images/icons/begateway.png:/var/www/html/images/icons/begateway.png
      - ./src/includes/modules/payment/begateway.php:/var/www/html/includes/modules/payment/begateway.php
      - ./src/includes/external/begateway-api-php:/var/www/html/includes/external/begateway-api-php

  vamshop:
    <<: *default

  mysql:
    image: mysql:5.5
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vamshop
